//! OpenAPI specification for HOBBS Web API.

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use super::dto::request::{
    AdminAddFeedRequest, AdminCreateBoardRequest, AdminCreateFolderRequest,
    AdminResetPasswordRequest, AdminUpdateBoardRequest, AdminUpdateFolderRequest,
    AdminUpdateRoleRequest, AdminUpdateStatusRequest, AdminUpdateUserRequest,
    ChangePasswordRequest, CreateFlatPostRequest, CreatePostRequest, CreateThreadRequest,
    LoginRequest, LogoutRequest, PaginationQuery, RefreshRequest, RegisterRequest, SendMailRequest,
    UpdateProfileRequest,
};
use super::dto::response::{
    AdminBoardResponse, AdminFolderResponse, AdminUserResponse, AuthorInfo, BoardResponse,
    FileResponse, FileUploadResponse, FolderResponse, LoginResponse, MailDetailResponse,
    MailListResponse, MeResponse, PaginationMeta, PostResponse, RefreshResponse, RssFeedResponse,
    RssItemResponse, ThreadResponse, UnreadCountResponse, UserDetailResponse, UserInfo,
    UserListResponse,
};
// Import the __path_ structs generated by utoipa::path macro
use super::handlers::{
    __path_admin_create_board,
    __path_admin_create_folder,
    __path_admin_delete_board,
    __path_admin_delete_folder,
    __path_admin_list_boards,
    __path_admin_list_folders,
    // Admin paths
    __path_admin_list_users,
    __path_admin_reset_password,
    __path_admin_update_board,
    __path_admin_update_folder,
    __path_admin_update_role,
    __path_admin_update_status,
    __path_admin_update_user,
    __path_change_password,
    __path_create_flat_post,
    // Board paths
    __path_create_thread,
    __path_create_thread_post,
    __path_delete_file,
    __path_delete_mail,
    __path_delete_post,
    __path_download_file,
    __path_get_board,
    __path_get_file,
    __path_get_folder,
    __path_get_mail,
    __path_get_my_profile,
    __path_get_thread,
    __path_get_unread_count,
    __path_get_user,
    __path_list_boards,
    __path_list_files,
    __path_list_flat_posts,
    // File paths
    __path_list_folders,
    // Mail paths
    __path_list_inbox,
    __path_list_sent,
    __path_list_thread_posts,
    __path_list_threads,
    // User paths
    __path_list_users,
    // Auth paths
    __path_login,
    __path_logout,
    __path_me,
    __path_refresh,
    __path_register,
    __path_send_mail,
    __path_update_my_profile,
    __path_upload_file,
};

/// Security scheme modifier for JWT bearer authentication.
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

/// OpenAPI documentation for HOBBS Web API.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "HOBBS API",
        description = "REST API for HOBBS - Hobbyist Bulletin Board System",
        version = "1.0.0",
        contact(
            name = "HOBBS Project",
            url = "https://github.com/h-o-soft/hobbs"
        ),
        license(
            name = "MIT",
            url = "https://opensource.org/licenses/MIT"
        )
    ),
    servers(
        (url = "/api", description = "API base path")
    ),
    tags(
        (name = "auth", description = "Authentication endpoints"),
        (name = "boards", description = "Board management"),
        (name = "threads", description = "Thread management"),
        (name = "posts", description = "Post management"),
        (name = "mail", description = "Private mail"),
        (name = "users", description = "User management"),
        (name = "rss", description = "RSS feed reader"),
        (name = "folders", description = "File folder management"),
        (name = "files", description = "File management"),
        (name = "admin", description = "Administration endpoints")
    ),
    paths(
        // Auth
        login,
        logout,
        refresh,
        register,
        me,
        // Boards
        list_boards,
        get_board,
        list_threads,
        create_thread,
        list_flat_posts,
        create_flat_post,
        // Threads
        get_thread,
        list_thread_posts,
        create_thread_post,
        // Posts
        delete_post,
        // Mail
        list_inbox,
        list_sent,
        get_mail,
        send_mail,
        delete_mail,
        get_unread_count,
        // Users
        list_users,
        get_user,
        get_my_profile,
        update_my_profile,
        change_password,
        // Folders
        list_folders,
        get_folder,
        // Files
        list_files,
        upload_file,
        get_file,
        download_file,
        delete_file,
        // Admin
        admin_list_users,
        admin_update_user,
        admin_update_role,
        admin_update_status,
        admin_reset_password,
        admin_list_boards,
        admin_create_board,
        admin_update_board,
        admin_delete_board,
        admin_list_folders,
        admin_create_folder,
        admin_update_folder,
        admin_delete_folder,
    ),
    components(
        schemas(
            // Request DTOs
            LoginRequest,
            LogoutRequest,
            RefreshRequest,
            RegisterRequest,
            PaginationQuery,
            CreateThreadRequest,
            CreatePostRequest,
            CreateFlatPostRequest,
            SendMailRequest,
            UpdateProfileRequest,
            ChangePasswordRequest,
            AdminUpdateUserRequest,
            AdminUpdateRoleRequest,
            AdminUpdateStatusRequest,
            AdminResetPasswordRequest,
            AdminCreateBoardRequest,
            AdminUpdateBoardRequest,
            AdminCreateFolderRequest,
            AdminUpdateFolderRequest,
            AdminAddFeedRequest,
            // Response DTOs
            PaginationMeta,
            LoginResponse,
            UserInfo,
            RefreshResponse,
            MeResponse,
            BoardResponse,
            ThreadResponse,
            PostResponse,
            AuthorInfo,
            MailListResponse,
            MailDetailResponse,
            UnreadCountResponse,
            UserListResponse,
            UserDetailResponse,
            RssFeedResponse,
            RssItemResponse,
            FolderResponse,
            FileResponse,
            FileUploadResponse,
            AdminUserResponse,
            AdminBoardResponse,
            AdminFolderResponse,
        )
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;
