//! OpenAPI specification for HOBBS Web API.

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use super::dto::request::{
    AdminAddFeedRequest, AdminCreateBoardRequest, AdminCreateFolderRequest,
    AdminResetPasswordRequest, AdminUpdateBoardRequest, AdminUpdateFolderRequest,
    AdminUpdateRoleRequest, AdminUpdateStatusRequest, AdminUpdateUserRequest,
    ChangePasswordRequest, CreateFlatPostRequest, CreatePostRequest, CreateThreadRequest,
    LoginRequest, LogoutRequest, PaginationQuery, RefreshRequest, RegisterRequest,
    SendMailRequest, UpdateProfileRequest,
};
use super::dto::response::{
    AdminBoardResponse, AdminFolderResponse, AdminUserResponse, AuthorInfo, BoardResponse,
    FileResponse, FileUploadResponse, FolderResponse, LoginResponse, MailDetailResponse,
    MailListResponse, MeResponse, PaginationMeta, PostResponse, RefreshResponse, RssFeedResponse,
    RssItemResponse, ThreadResponse, UnreadCountResponse, UserDetailResponse, UserInfo,
    UserListResponse,
};
// Import the __path_ structs generated by utoipa::path macro
use super::handlers::{
    // Auth paths
    __path_login, __path_logout, __path_me, __path_refresh, __path_register,
    // Board paths
    __path_create_thread, __path_get_board, __path_list_boards, __path_list_threads,
};

/// Security scheme modifier for JWT bearer authentication.
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

/// OpenAPI documentation for HOBBS Web API.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "HOBBS API",
        description = "REST API for HOBBS - Hobbyist Bulletin Board System",
        version = "1.0.0",
        contact(
            name = "HOBBS Project",
            url = "https://github.com/h-o-soft/hobbs"
        ),
        license(
            name = "MIT",
            url = "https://opensource.org/licenses/MIT"
        )
    ),
    servers(
        (url = "/api", description = "API base path")
    ),
    tags(
        (name = "auth", description = "Authentication endpoints"),
        (name = "boards", description = "Board management"),
        (name = "threads", description = "Thread management"),
        (name = "posts", description = "Post management"),
        (name = "mail", description = "Private mail"),
        (name = "users", description = "User management"),
        (name = "rss", description = "RSS feed reader"),
        (name = "folders", description = "File folder management"),
        (name = "files", description = "File management"),
        (name = "admin", description = "Administration endpoints")
    ),
    paths(
        // Auth
        login,
        logout,
        refresh,
        register,
        me,
        // Boards
        list_boards,
        get_board,
        list_threads,
        create_thread,
    ),
    components(
        schemas(
            // Request DTOs
            LoginRequest,
            LogoutRequest,
            RefreshRequest,
            RegisterRequest,
            PaginationQuery,
            CreateThreadRequest,
            CreatePostRequest,
            CreateFlatPostRequest,
            SendMailRequest,
            UpdateProfileRequest,
            ChangePasswordRequest,
            AdminUpdateUserRequest,
            AdminUpdateRoleRequest,
            AdminUpdateStatusRequest,
            AdminResetPasswordRequest,
            AdminCreateBoardRequest,
            AdminUpdateBoardRequest,
            AdminCreateFolderRequest,
            AdminUpdateFolderRequest,
            AdminAddFeedRequest,
            // Response DTOs
            PaginationMeta,
            LoginResponse,
            UserInfo,
            RefreshResponse,
            MeResponse,
            BoardResponse,
            ThreadResponse,
            PostResponse,
            AuthorInfo,
            MailListResponse,
            MailDetailResponse,
            UnreadCountResponse,
            UserListResponse,
            UserDetailResponse,
            RssFeedResponse,
            RssItemResponse,
            FolderResponse,
            FileResponse,
            FileUploadResponse,
            AdminUserResponse,
            AdminBoardResponse,
            AdminFolderResponse,
        )
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;
